---
name: "Subtitle Sorter"
guid: "e1f630f5-6605-43be-96d8-d89a39c4d946"
version: "1.0.0.0.1"
targetAbi: "10.11.0.0"
framework: "net8.0"
overview: "A generic plugin with a filter system for detecting subtitles hidden in subfolders"
description: >
  Detect subtitles hidden in subfolders and link them correctly for Jellyfin.
category: "General"
owner: "BennyStarfighter"
artifacts:
  - "Jellyfin.Plugin.SubtitleSorter.dll"
changelog: >
  - Updated to Jellyfin 10.11 ABI
  - Updated build to .NET 8
  - Fixed SortOrder and OrderBy API breaking changes
